site_name: RICOH THETA Development on Linux
site_url: 
site_description: Configure Linux computers like the Jetson Nano to stream and use RICOH THETA USB API
repo_url: 
repo_name: 
site_author: Oppkey
google_analytics: ['UA-73311422-1', 'auto']

theme:
  name: material
  # custom_dir: 'theme'
  palette:
    primary: 'light green'
    accent: 'lime'
  logo: images/logo-white.png
  favicon: images/logo-white.png

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/theta360developers'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/theta360dev'
    - icon: fontawesome/brands/facebook
      link: 'https://www.facebook.com/theta360guide/'
  analytics:
    provider: google
    property: UA-73311422-1        

nav:
  - Home: index.md
  - Equipment: equipment.md
  - Software: software.md
  - Demos: demos.md
  - Examples: examples.md
  - USB API: usb_api.md
  - Camera: camera.md
  - Optimization: optimization.md
  - Help: help.md
  - Meetup Archive: meetup.md


# plugins:
#   - search
  # - pdf-export:
  #     media_type: print
  #     combined: true  
