site_name: RICOH THETA USB API For Jetson Nano
site_url: 
site_description: Configure Jetson Nano to use RICOH THETA USB API
repo_url: 
repo_name: 
site_author: Oppkey
google_analytics: ['UA-73311422-1', 'auto']

theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: 'light green'
    accent: 'lime'
  logo: images/logo-white.png
  favicon: images/logo-white.png
  icon:
    logo: assets/images/logo.png

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/theta360developers'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/theta360dev'
    - icon: fontawesome/brands/facebook
      link: 'https://www.facebook.com/theta360guide/'

nav:
  - Home: index.md
  - USB API: usb_api.md

  
